#!/bin/bash
echo -e "\e[31m"
figlet TTY-msg
echo -e "\e[0m"
echo "Send a message to all active TTY Sessions"
echo
if [[ $# -eq 0 ]]; then 
	echo "Usage: $0 <message to send within quotation marks>"
	echo ""
	exit 1
fi
ls -f /dev/pts/ >> ttys.tmp
sed -i '1d;2d;$d' ttys.tmp
while read i; do sudo echo "" >> /dev/pts/$i; sudo echo "$1" >> /dev/pts/$i; sudo echo "" >>/dev/pts/$i; done < ttys.tmp
echo
echo -e "\e[33mDone!"
rm ttys.tmp
exit
